// Transcript helper: load voice JSON + look up word-level timestamps.
// Generated by scripts/transcribe-voices.py (faster-whisper).
//
// Usage in a scene:
//   import transcript from "../../../public/voice/03_Chapter_4.json";
//   import { frameFor } from "../../lib/transcript";
//   const frame = frameFor(transcript, "single line");
//
// JSON sidecar files live next to each voice .mp3:
//   voice/03_Chapter_4.mp3  →  voice/03_Chapter_4.json
//
// Each entry has:
//   - file, language, duration, text
//   - segments[]: {start, end, text, words: [{start, end, word, prob}]}

export type Word = {
  start: number; // seconds
  end: number;
  word: string;
  prob: number;
};

export type Segment = {
  start: number;
  end: number;
  text: string;
  words: Word[];
};

export type Transcript = {
  file: string;
  language: string;
  duration: number;
  text: string;
  segments: Segment[];
};

const FPS_DEFAULT = 30;

export function frameFor(
  transcript: Transcript,
  text: string,
  fps: number = FPS_DEFAULT,
): number {
  const flat = transcript.segments.flatMap((s) => s.words);
  const w = flat.find((w) =>
    w.word.toLowerCase().includes(text.toLowerCase()),
  );
  return w ? Math.round(w.start * fps) : -1;
}

export function rangeFor(
  transcript: Transcript,
  startText: string,
  endText: string,
  fps: number = FPS_DEFAULT,
): [number, number] {
  const flat = transcript.segments.flatMap((s) => s.words);
  const a = flat.find((w) =>
    w.word.toLowerCase().includes(startText.toLowerCase()),
  );
  const b = flat.find((w) =>
    w.word.toLowerCase().includes(endText.toLowerCase()),
  );
  return [
    a ? Math.round(a.start * fps) : -1,
    b ? Math.round(b.end * fps) : -1,
  ];
}

export function textBefore(
  transcript: Transcript,
  frame: number,
  fps: number = FPS_DEFAULT,
): string {
  const t = frame / fps;
  const words = transcript.segments
    .flatMap((s) => s.words)
    .filter((w) => w.end <= t);
  return words.map((w) => w.word).join(" ");
}
